version: "3"
services:
  springboot-app1:
    container_name: c2
    image: employee2
    restart: always
    build: .
    ports:
        - 8099:8098
    environment: 
      MYSQL_HOST: mysqldb5
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  c1:
    container_name: mysqldb5
    image: mysql
  
    ports:
       - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root   